config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    member do
      post 'join'
      post 'leave'
    end
  end
  devise_for :users
  root to: 'rooms#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }

  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
  has_many :room_users
  has_many :participants, :through => :room_users, :class_name => 'User', :foreign_key => 'user_id'
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :participant, :class_name => 'User', :foreign_key => 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_room, only: [:show, :edit, :update, :destroy, :join, :leave]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    @messages = @room.messages
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    respond_to do |format|
      if @room.participants << current_user
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def leave
    respond_to do |format|
      if @room.participants.delete(current_user)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railschat</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>  
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class='messages'>
  <p><%= message.user.email %></p>
  <p><%= message.content %></p>
</div>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.user.email %></td>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= link_to 'Enter Room', room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= link_to "Channel List", rooms_path() %>

<% if @room.participants.count > 0 %>
  <% if @room.participants.find(current_user.id) %>
    <%= link_to "Leave Room", { :controller => :rooms, :action => :leave }, { :method => :post } %>
  <% else %>
    <%= link_to "Join Room", { :controller => :rooms, :action => :join }, { :method => :post } %>
  <% end %>
<% else %>
  <%= link_to "Join Room", { :controller => :rooms, :action => :join }, { :method => :post } %>
<% end %>

<h1><%= @room.name %></h1>

<div id='messages'>
  <%= render @messages %>
</div>

<form>
  <input type='hidden' name='room_id' value='<%= @room.id %>'>
  <label>Say something</label>
  <input type='text' data-behavior='room_speaker'>
</form>